#ifndef GUI_HPP
#define GUI_HPP

#include "GUIslice.h"
#include "GUIslice_drv.h"
#include "GUIslice_ex.h"

namespace Gui
{
enum Page
{
  MAIN = 0,
  PLAY1,
  PLAY2,
  PLAY3,
  CREATIVE1,
  CREATIVE2,
  MAX_PAGES,
};

enum Elem
{
  MAIN_BOX,
  MAIN_TITLE1,
  MAIN_TITLE2,
  MAIN_BUTTON_PLAY,
  MAIN_BUTTON_CREATIVE,

  PLAY1_BOX,
  PLAY1_TITLE1,
  PLAY1_TITLE2,
  PLAY1_BUTTON_BACK,
  PLAY1_BUTTON_FORWARD,
  PLAY1_BUTTON_FILE1,
  PLAY1_BUTTON_FILE2,
  PLAY1_BUTTON_FILE3,
  PLAY1_BUTTON_FILE4,
  PLAY1_BUTTON_FILE5,
  PLAY1_BUTTON_FILE6,
  PLAY1_BUTTON_FILE7,
  PLAY1_BUTTON_FILE8,
  PLAY1_BUTTON_FILE9,
  PLAY1_BUTTON_FILE10,
  PLAY1_BUTTON_FILE11,
  PLAY1_BUTTON_FILE12,

  PLAY2_BOX,
  PLAY2_TITLE1,
  PLAY2_TITLE2,
  PLAY2_BUTTON_BACK,
  PLAY2_BUTTON_GO,

  PLAY3_BLACK,

  CREATIVE1_BOX,
  CREATIVE1_TITLE1,
  CREATIVE1_TITLE2,
  CREATIVE1_BUTTON_BACK,
  CREATIVE1_BUTTON_GO,
  CREATIVE1_SLIDER_R,
  CREATIVE1_SLIDER_G,
  CREATIVE1_SLIDER_B,
  CREATIVE1_COLORBOX,

  CREATIVE2_DUMMY,

  MAX_ELEMS,

  MAIN_START      = MAIN_BOX,
  MAIN_END        = MAIN_BUTTON_CREATIVE,
  PLAY1_START     = PLAY1_BOX,
  PLAY1_END       = PLAY1_BUTTON_FILE12,
  PLAY2_START     = PLAY2_BOX,
  PLAY2_END       = PLAY2_BUTTON_GO,
  PLAY3_START     = PLAY3_BLACK,
  PLAY3_END       = PLAY3_BLACK,
  CREATIVE1_START = CREATIVE1_BOX,
  CREATIVE1_END   = CREATIVE1_COLORBOX,
  CREATIVE2_START = CREATIVE2_DUMMY,
  CREATIVE2_END   = CREATIVE2_DUMMY,
};

enum Font
{
  TEXT = 0,
  TITLE,
  MAX_FONTS,
};

extern const char *fileToLoad;

void init();
void update();
}

#endif

// vim: et ts=2
